---
title: "cleaning"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
# library import
library(tidyverse)
library(chron)
```

```{r}
# data import
data <- read_delim("data.dat", "\t", escape_double = FALSE, trim_ws = TRUE)

# 96 patients and remove comments column
data <- data[1:96,] %>% select(-Comments)

# Interested varibale, please refers to meta.dox for their meanings.
col_selected <- c(1,2,4,6,10,11,12,14,17,20,23,
                  24,25,26,32,33,55,59,60,82,84,
                  89,90,91,93)

data <- data[,col_selected]

# name column with code
colnames(data) <- paste0("var_",col_selected)

# Convert Time to do US into minutes
data$var_32 <- 60 * 24 * as.numeric(times(data$var_32))
data$var_59 <- 60 * 24 * as.numeric(times(data$var_59))

# fill missing values in the favor of SAS format
for(i in 1:length(sapply(data,class))){
  if('character' %in% sapply(data,class)[i]){
    data[,i] <- replace(data[,i],is.na(data[,i])," ")
    data[,i] <- replace(data[,i],data[,i]=='n/a'," ")
  }else{
    data[,i] <- replace(data[,i],is.na(data[,i]),".")
    data[,i] <- replace(data[,i],data[,i]=='n/a',".")
  }
}
```

```{r}
# convert to CSV for SAS
# This is the last step of this Rmd, Do Not Run til we finish cleaning
write.csv(data,'appUS.csv')
```
